version: 2
jobs:
  test:
    docker:
      - image: circleci/ruby:2.4.4
        environment:
          RUNTIME_ENV: test
    steps:
      - checkout
      - run:
          name: Install Ruby gems
          command: |
            bundle check --path=vendor/bundle || bundle install --path=vendor/bundle --jobs=4 --retry=3
      - run:
          name: Set up test output directory
          command: sudo install -o circleci -d ~/rspec
      - run:
          name: RSpec
          command: |
            bundle exec rspec \
              --color \
              --require spec_helper \
              --format documentation \
              --format RspecJunitFormatter \
              --out ~/rspec/rspec.xml \
              $(circleci tests glob "spec/**/*_spec.rb" | circleci tests split --split-by=timings --timings-type=filename)
      - store_artifacts:
          path: ~/rspec
      - store_test_results:
          path: ~/rspec
workflows:
  version: 2
  test_build:
    jobs:
      - test
